server:
  port: 8092
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 日志
logging:
  level:
    root:  info
  config: classpath:logback-spring.xml

# 微信公众号对接
weixin:
  config:
    originalid: gh_5d56e8de7de7
    token: 3387
    app-id: wxa472b5da198cf02f
    app-secret: 90d671bf7122c329ee6a6b980ca7cfc3
    # 登陆成功模板id
    template-id: NmPOTnHL_rfG1qgCLQ1cSgCr4GcWb3QUA89-Xl6bjiY

# MySql数据库配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

  redis:
    host: 127.0.0.1
    port: 16379
    timeout: 3000
    password: 123456

# 支付宝支付
alipay:
  enable: true
  app_id: 9021000151609030
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC//E//GRmWBb8dqJ4LhUIrfYaTqw5k5nw2eZCV3t4t4PPO2vy7V3gmUWt9OH57g+fsUjlIfndqA2SYf4dUT5aw2dsi/xCMqRrBCqYKmwGvEdkWXuNpsuMQlnudhBnJ1n9ddVE1jz1onQt5vSB4prBhZqZSt2qm4bLUv/gJqRRPO75OVsD6rwHfwo49+4J45/zQTUOODQA/tZfQEw3rVgmeUppv9lqlBto9fcuSpu4ls9wf0E1Yp65busX4bEoOUdR88hdmCiNd5e8ZquhagiRPXFT/1xytqg8vp237K0SO+5Gr+89QHQ9gJcThiGIRjcJnnLle1+n3+zwOzA4AAW29AgMBAAECggEASZNMpRrdb10sbRVd3FRpk3k7xgPcNFcQa2ATRRxwUWzQgwnxqWpQJX82jnrEHlni2/J2+Y1d/kbmmnrlRi5qNcSH8tWFZiK4mhqWn6Hf91QDuksLJErmMkk5fphNuch2bz6yrLAEfL8S0sjkVNis5+cK/tBEE0iT3Gzlhe5CVkqIcZA/okFPGXC1lRcgndrb+qTN+O44svSh4rjVSMJLUyvZyEpDJ33AqqXwNq/o2zNghNFkl+p/VWg09A+GNljZ5ibNXIHi6vPvJXwGNwFAtek5s078nucxRPbTGThkwG3OFyv4IMUFjyuLidYQSsnom69GbwMyizla+pMiBOXFEQKBgQDzLJ58bVB9YxRKyxxOst5m6cCiuq1p9JzeAxO8r2jwb0UdVPS8iCXF7/66NPMq/7jMKGZ1fBAe1Iw+fef0BJ1lljWJU6oV1aikb2/D047zCcuWQYZ8X7lZWWDtmQCOsxJRcAl2XqAS/QJCij4hZT9mEfic2fA+GqlwS1pGWCqg2wKBgQDKHIjrr+R6BYzh0zTDRuDrGKYQHMJG0arhb8R8Jkf5xnvi6Kdlv+mZSwYH5pv/YD1mPEvxnZHR0ofqYsiQMuSUvy6DrqhN+3gvIVS/9JaQZgo/AMOuovMIUJY/o5GDqWkqAQ13mG7a/nbbnXC39bZAOimnr/usiG+JRFccF3jDRwKBgQCY30QDFPW03cS0AFwbXXdTW0AvDQxXv9+d8nFF/UALZugcOHxiyXR1qxqIFSGJtpmGPx+qXAQGXbiM0LoxPXV1l6iwXFhgwaDzPtsUULtdLps+KpNRPRxYf0fgFn+zNgAeEkDgmTwos8Xn7uCAPhZNJJ8WfCv73ucGIVjvQB4MYQKBgQCA2+CQI/zPr2o7MKWbOz17pqN58lwLOvJv+QqU/PM21M13xk20Gb+d9K9LqkQbdgivfhINYiDuXgQ58/FbvpbuH1ZQrrKvxXzCz8Vw/UhhmC1ALgSU+19oFbk1qdvEzeY22aT0c0N6bHLrYl3Ta91e5bZZK2KShgpWwjOnvW9JUQKBgHbD5K/hzB5BEWzjNE0G+Xw/UjlzwOn5pMLCmPNPMTq4u0gHiNI2lTAmK7GPqSr2wCPoVk8bhBUveQC3h1SWgxI8PfC55HPSb3qs/UZRZRuZIa4Xfns35OuccNCOAoHcCqZzoVlpIHxiOkR9t0pgmiZ+hpet+UZdE4dCmB/koKtJ7
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6/6e7aQWI2noA8TQoCl4qgLyL+/ATWXf34unRcLwyhuCywQjkO4RJKzGYdUKw16gFJOsMvCIUFViY9ZFKdh+gZrDbq8KVbVZcsfQ8hmaSNRYaudsFcenfRsnfBu3iUqMzxjiJwnBHSMZDZpGKkAQ94SwTWc8d77Ry43kwwjY+Cc+GjM1/JuaXhotvuw30SqIa6ZX2hhDjfDf1jzvCyj85Xq9uKrU2oBbTFPvpOVGHcX+BGODU8tONMhU/BpEgVTRpmZ6IpHollHQILPlZKyWdl0uGuXOWm+Fp64YlVIZhLzgt44f8D5IQIADcLDgGZFCM7U2949WJ6Y00HGeLfHMnQIDAQAB
  # 回调
  notify_url: http://banxia.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml


